// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sensor-data/sensorData.proto

/*
Package sensor_data is a generated protocol buffer package.

It is generated from these files:
	sensor-data/sensorData.proto

It has these top-level messages:
	SensorData
*/
package sensor_data

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SensorData struct {
	Timestamp             *uint64  `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	TemperatureSampleRate *uint32  `protobuf:"varint,2,opt,name=temperatureSampleRate" json:"temperatureSampleRate,omitempty"`
	HumiditySampleRate    *uint32  `protobuf:"varint,3,opt,name=humiditySampleRate" json:"humiditySampleRate,omitempty"`
	AudioSampleRate       *uint32  `protobuf:"varint,4,opt,name=audioSampleRate" json:"audioSampleRate,omitempty"`
	LightSampleRate       *uint32  `protobuf:"varint,5,opt,name=lightSampleRate" json:"lightSampleRate,omitempty"`
	TemperatureData       []uint32 `protobuf:"varint,6,rep,packed,name=temperatureData" json:"temperatureData,omitempty"`
	HumidityData          []uint32 `protobuf:"varint,7,rep,packed,name=humidityData" json:"humidityData,omitempty"`
	AudioData             []uint32 `protobuf:"varint,8,rep,packed,name=audioData" json:"audioData,omitempty"`
	LightData             []uint32 `protobuf:"varint,9,rep,packed,name=lightData" json:"lightData,omitempty"`
	ChipID                *uint32  `protobuf:"varint,10,opt,name=chipID" json:"chipID,omitempty"`
	XXX_unrecognized      []byte   `json:"-"`
}

func (m *SensorData) Reset()                    { *m = SensorData{} }
func (m *SensorData) String() string            { return proto.CompactTextString(m) }
func (*SensorData) ProtoMessage()               {}
func (*SensorData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SensorData) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *SensorData) GetTemperatureSampleRate() uint32 {
	if m != nil && m.TemperatureSampleRate != nil {
		return *m.TemperatureSampleRate
	}
	return 0
}

func (m *SensorData) GetHumiditySampleRate() uint32 {
	if m != nil && m.HumiditySampleRate != nil {
		return *m.HumiditySampleRate
	}
	return 0
}

func (m *SensorData) GetAudioSampleRate() uint32 {
	if m != nil && m.AudioSampleRate != nil {
		return *m.AudioSampleRate
	}
	return 0
}

func (m *SensorData) GetLightSampleRate() uint32 {
	if m != nil && m.LightSampleRate != nil {
		return *m.LightSampleRate
	}
	return 0
}

func (m *SensorData) GetTemperatureData() []uint32 {
	if m != nil {
		return m.TemperatureData
	}
	return nil
}

func (m *SensorData) GetHumidityData() []uint32 {
	if m != nil {
		return m.HumidityData
	}
	return nil
}

func (m *SensorData) GetAudioData() []uint32 {
	if m != nil {
		return m.AudioData
	}
	return nil
}

func (m *SensorData) GetLightData() []uint32 {
	if m != nil {
		return m.LightData
	}
	return nil
}

func (m *SensorData) GetChipID() uint32 {
	if m != nil && m.ChipID != nil {
		return *m.ChipID
	}
	return 0
}

func init() {
	proto.RegisterType((*SensorData)(nil), "sensor_data.SensorData")
}

func init() { proto.RegisterFile("sensor-data/sensorData.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0xcf, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x06, 0x60, 0xd2, 0xd4, 0x6a, 0x46, 0x4b, 0x65, 0x40, 0xc9, 0xa1, 0x87, 0xe0, 0x41, 0x72,
	0xd0, 0x7a, 0xf1, 0x09, 0xa4, 0x17, 0xaf, 0xe9, 0x03, 0xc8, 0x60, 0x16, 0xb3, 0xd0, 0x75, 0x97,
	0xcd, 0xe4, 0xe0, 0x8b, 0xf8, 0xbc, 0xb2, 0x13, 0xdd, 0xac, 0xa1, 0xb7, 0xe4, 0xff, 0xbf, 0x81,
	0x7f, 0x61, 0xdb, 0xab, 0xcf, 0xde, 0xfa, 0xc7, 0x96, 0x98, 0x9e, 0xc6, 0xef, 0x3d, 0x31, 0xed,
	0x9c, 0xb7, 0x6c, 0xf1, 0x72, 0x4c, 0xde, 0x42, 0x7b, 0xf7, 0x9d, 0x03, 0x1c, 0xa2, 0xc0, 0x2d,
	0x14, 0xac, 0x8d, 0xea, 0x99, 0x8c, 0x2b, 0xb3, 0x2a, 0xab, 0x97, 0xcd, 0x14, 0xe0, 0x33, 0xdc,
	0xb0, 0x32, 0x4e, 0x79, 0xe2, 0xc1, 0xab, 0x03, 0x19, 0x77, 0x54, 0x0d, 0xb1, 0x2a, 0x17, 0x55,
	0x56, 0xaf, 0x9b, 0xd3, 0x25, 0xee, 0x00, 0xbb, 0xc1, 0xe8, 0x56, 0xf3, 0x57, 0x72, 0x92, 0xcb,
	0xc9, 0x89, 0x06, 0x6b, 0xd8, 0xd0, 0xd0, 0x6a, 0x9b, 0xe0, 0xa5, 0xe0, 0x79, 0x1c, 0xe4, 0x51,
	0x7f, 0x74, 0x9c, 0xc8, 0xb3, 0x51, 0xce, 0x62, 0x7c, 0x80, 0x4d, 0x32, 0x2e, 0x3c, 0xb5, 0x5c,
	0x55, 0x79, 0xbd, 0x7e, 0x59, 0x5c, 0x67, 0xcd, 0xbc, 0xc2, 0x7b, 0xb8, 0xfa, 0xdb, 0x25, 0xf4,
	0x3c, 0xd2, 0x7f, 0x39, 0x56, 0x50, 0xc8, 0x24, 0x41, 0x17, 0x11, 0x4d, 0x61, 0x10, 0x32, 0x45,
	0x44, 0x31, 0x89, 0x18, 0xe2, 0x2d, 0xac, 0xde, 0x3b, 0xed, 0x5e, 0xf7, 0x25, 0xc8, 0xf4, 0xdf,
	0xbf, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x1a, 0x27, 0xa3, 0xc4, 0x01, 0x00, 0x00,
}
